import { Plugin } from 'vite';
import { readFile, writeFile, stat } from 'fs/promises';
import { dirname, join, relative, resolve } from 'path';
import { existsSync } from 'fs';
import * as ejs from 'ejs';

interface EjsFormioOptions {
  /**
   * Directory containing EJS templates
   */
  templateDir?: string;
  /**
   * File extension for EJS templates
   */
  templateExtension?: string;
  /**
   * Watch for changes during development
   */
  watch?: boolean;
}

/**
 * Custom Vite plugin to compile EJS templates for FormIO
 * Converts .ejs files to .ejs.js modules that can be imported
 */
export function ejsFormioPlugin(options: EjsFormioOptions = {}): Plugin {
  const {
    templateDir = 'resources/js/lib/tailwind-formio/src/templates',
    templateExtension = '.ejs',
    watch = true
  } = options;

  const compiledFiles = new Map<string, string>();

  const compileEjsTemplate = async (ejsFilePath: string): Promise<string> => {
    try {
      let templateContent = await readFile(ejsFilePath, 'utf-8');
      
      // Convert FormIO's custom delimiters to standard EJS delimiters
      // Based on original gulp implementation:
      // {% %} → JavaScript code execution
      // {{ }} → Unescaped HTML output (<%- %>)
      // {{{ }}} → Escaped HTML output (<%= %>)
      
      // First, convert {{{ }}} to <%= %> for escaped output
      templateContent = templateContent.replace(/\{\{\{\s*([\s\S]*?)\s*\}\}\}/g, '<%= $1 %>');
      
      // Then, convert {{ }} to <%- %> for unescaped output
      templateContent = templateContent.replace(/\{\{\s*([\s\S]*?)\s*\}\}/g, '<%- $1 %>');
      
      // Finally, convert {% %} to <% %> for JavaScript code
      templateContent = templateContent.replace(/\{%\s*([\s\S]*?)\s*%\}/g, '<% $1 %>');
      
      // Compile the EJS template to a function using standard EJS delimiters
      const compiledTemplate = ejs.compile(templateContent, {
        filename: ejsFilePath,
        client: true, // Generate client-side template function
        strict: true,
        localsName: 'ctx', // Use 'ctx' as the data parameter name (FormIO convention)
      });

      // Generate the JavaScript module content
      const moduleContent = `// Auto-generated from ${relative(process.cwd(), ejsFilePath)}
// Do not edit this file directly - it will be overwritten

const template = ${compiledTemplate.toString()};

export default function(ctx = {}) {
  // Provide default context values commonly used in FormIO templates
  const defaultCtx = {
    wizardKey: 'wizard',
    buttonOrder: ['previous', 'next', 'cancel', 'submit'],
    buttons: {
      cancel: true,
      previous: true,
      next: true,
      submit: true
    },
    disableWizardSubmit: false,
    t: (key) => {
      // Simple translation fallback
      const translations = {
        cancel: 'Cancel',
        previous: 'Previous',
        next: 'Next',
        submit: 'Submit',
        cancelButtonAriaLabel: 'Cancel',
        previousButtonAriaLabel: 'Previous',
        nextButtonAriaLabel: 'Next',
        submitButtonAriaLabel: 'Submit'
      };
      return translations[key] || key;
    },
    ...ctx
  };

  return template(defaultCtx);
}`;

      return moduleContent;
    } catch (error) {
      console.error(`Error compiling EJS template ${ejsFilePath}:`, error);
      throw error;
    }
  };

  const processEjsFile = async (ejsFilePath: string) => {
    const outputPath = ejsFilePath + '.js';
    
    try {
      // Check if we need to recompile
      const [ejsStat, jsStat] = await Promise.all([
        stat(ejsFilePath),
        stat(outputPath).catch(() => null)
      ]);

      if (jsStat && ejsStat.mtime <= jsStat.mtime) {
        // Output is newer than source, skip compilation
        return;
      }

      console.log(`Compiling EJS template: ${relative(process.cwd(), ejsFilePath)}`);
      
      const moduleContent = await compileEjsTemplate(ejsFilePath);
      await writeFile(outputPath, moduleContent, 'utf-8');
      
      compiledFiles.set(ejsFilePath, outputPath);
      
    } catch (error) {
      console.error(`Failed to process ${ejsFilePath}:`, error);
    }
  };

  const findAndProcessEjsFiles = async (dir: string) => {
    const { readdir } = await import('fs/promises');
    
    try {
      const entries = await readdir(dir, { withFileTypes: true });
      
      const promises = entries.map(async (entry) => {
        const fullPath = join(dir, entry.name);
        
        if (entry.isDirectory()) {
          await findAndProcessEjsFiles(fullPath);
        } else if (entry.isFile() && entry.name.endsWith(templateExtension)) {
          await processEjsFile(fullPath);
        }
      });
      
      await Promise.all(promises);
    } catch (error) {
      console.error(`Error processing directory ${dir}:`, error);
    }
  };

  return {
    name: 'ejs-formio',
    
    async buildStart() {
      // Process all EJS files at the start of the build
      const templatePath = resolve(templateDir);
      if (existsSync(templatePath)) {
        await findAndProcessEjsFiles(templatePath);
      }
    },

    configureServer(server) {
      if (!watch) return;

      // Watch for EJS file changes during development
      server.ws.on('connection', () => {
        const watcher = server.watcher;
        
                 watcher.on('change', async (filePath) => {
           if (filePath.endsWith(templateExtension) && filePath.includes(templateDir)) {
             await processEjsFile(filePath);
             
             // Trigger HMR for the corresponding .js file
             server.ws.send({
               type: 'full-reload'
             });
           }
         });

        watcher.on('add', async (filePath) => {
          if (filePath.endsWith(templateExtension) && filePath.includes(templateDir)) {
            await processEjsFile(filePath);
          }
        });
      });
    },

    resolveId(id, importer) {
      // Handle imports of .ejs.js files
      if (id.endsWith('.ejs.js') && importer) {
        const resolvedPath = resolve(dirname(importer), id);
        if (existsSync(resolvedPath)) {
          return resolvedPath;
        }
        
        // Check if the corresponding .ejs file exists and compile it
        const ejsPath = resolvedPath.replace('.ejs.js', '.ejs');
        if (existsSync(ejsPath)) {
          // Queue compilation
          processEjsFile(ejsPath).catch(console.error);
          return resolvedPath;
        }
      }
      return null;
    },

    load(id) {
      // Load compiled .ejs.js files
      if (id.endsWith('.ejs.js') && existsSync(id)) {
        return readFile(id, 'utf-8');
      }
      return null;
    }
  };
} 